### ISSUE TITLE
bug -- velocity fields?

### ISSUE THREAD

**Issue by mpatir** [kmhess/SoFiA-image-pipeline#71]
Hi, 

I am getting a strange bug when making velocity fields. Is there a way to fix this?

Please see the error log below: 

```
		-Source 26: SoFiA J060411.74-393134.7.
	Start making spatial images.
	Found 32.1 arcsec by 29.8 arcsec beam with PA=118.0 deg in primary header.
	Found J2000.0 equinox in header.
	Found CTYPE3 spectral axis type VRAD in header.
	No SPECSYS, VELREF, or reference frame in CTYPE3, assuming data in TOPOCENT reference frame.
	The first HI contour defined at SNR = [3.0, 4.0] has level = 7.384e+01 (mom0 data units).
	No user image given. Proceeding with the download of any requested archive images.
WARNING: AstropyDeprecationWarning: The truth value of a Quantity is ambiguous. In the future this will raise a ValueError. [astropy.units.quantity]
WARNING: InputWarning: Coordinate string is being interpreted as an ICRS coordinate. [astroquery.utils.commons]
	Survey image retrieved from DSS2 Blue.
	a3376_new_f_nodil_pbcorr_figures/a3376_new_f_nodil_pbcorr_26_mom0_dss2blue.png already exists. Will not overwrite.
	a3376_new_f_nodil_pbcorr_figures/a3376_new_f_nodil_pbcorr_26_mom0.png already exists. Will not overwrite.
	a3376_new_f_nodil_pbcorr_figures/a3376_new_f_nodil_pbcorr_26_snr.png already exists. Will not overwrite.
	Making velocity field.
	WARNING: Assuming channels are uniform width in velocity.
	WARNING: Assuming channels are uniform width in velocity.
/home/username/.local/lib/python3.9/site-packages/astropy/visualization/wcsaxes/core.py:234: UserWarning: No contour levels were found within the data range.
  cset = super().contour(*args, **kwargs)
Traceback (most recent call last):
  File "/usr/local/bin/sofia_image_pipeline", line 33, in <module>
    sys.exit(load_entry_point('sofia-image-pipeline', 'console_scripts', 'sofia_image_pipeline')())
  File "/home/username/Softwares/SoFiA-image-pipeline/src/image_pipeline.py", line 201, in main
    make_images.main(source, src_basename, opt_view=opt_view, suffix=suffix, sofia=sofia, beam=beam,
  File "/home/username/Softwares/SoFiA-image-pipeline/src/make_images.py", line 939, in main
    make_mom1(source, src_basename, cube_params, patch, opt_head, opt_view, HIlowest, suffix=suffix, sofia=2)
  File "/home/username/Softwares/SoFiA-image-pipeline/src/make_images.py", line 521, in make_mom1
    cbar.add_lines(cf)
  File "/home/username/.local/lib/python3.9/site-packages/matplotlib/colorbar.py", line 748, in add_lines
    return self.add_lines(
  File "/home/username/.local/lib/python3.9/site-packages/matplotlib/colorbar.py", line 779, in add_lines
    fac = np.max(linewidths) / 72
  File "<__array_function__ internals>", line 5, in amax
  File "/home/username/.local/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2733, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/home/username/.local/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by kmhess** [comment]
Hi @mpatir, interesting--I haven't seen this error before.  It's failing to plot the colorbar for the mom1 map.  Can you say a little bit about this source?  Is it a single channel source?  Does it have a valid mom1 map--one that isn't all nan's or negatives or something weird like that?  Have you tried updating to the latest version of SIP?  A while ago, @paoloserra put in a catch for single channel sources.  I never had to deal with them, but this might have been the same error message he got.

As another aside, SIP thinks your cube is in VRAD.  I haven't had a true VRAD cube to test things on, so could you confirm that it's recognizing what's in the header correctly?  I'd also be curious if you have another way to check the values in the moment maps or spectra, if you think SIP is calculating/plotting the velocity values correctly.  It would be very valuable feedback.  Thanks!
